// Généré depuis public/icons — un fichier SVG par icône
export type IconName =
  | 'activity'
  | 'alert'
  | 'archive'
  | 'baby'
  | 'bank'
  | 'book'
  | 'bug'
  | 'calendar'
  | 'check'
  | 'check-circle'
  | 'clock'
  | 'close'
  | 'dashboard'
  | 'edit'
  | 'excel'
  | 'eye'
  | 'eye-off'
  | 'file'
  | 'folder'
  | 'hash'
  | 'heart'
  | 'help'
  | 'history'
  | 'lock'
  | 'login'
  | 'logout'
  | 'menu'
  | 'microscope'
  | 'money'
  | 'moon'
  | 'package'
  | 'pill'
  | 'plus'
  | 'search'
  | 'settings'
  | 'stethoscope'
  | 'sun'
  | 'trash'
  | 'trending'
  | 'user'
  | 'user-plus'
  | 'users'

export type IconSize = 'sm' | 'md' | 'lg' | 'xl' | 'xxl'
